#! /bin/bash

n=`mktemp`
s=`mktemp`
for l in {A..Z}; do
  curl -s "https://build.opensuse.org/build/devel:languages:perl:CPAN-$l/_result?repository=openSUSE_13.2&arch=x86_64" | sed -e "s,nothing,\nnothing,g" >> $n
  curl -s "https://build.opensuse.org/build/devel:languages:perl:CPAN-$l/_result?repository=openSUSE_13.2&arch=x86_64&code=succeeded" | grep package= | sed -e 's,.*package=",,; s,".*,,' >> $s
done
n2=`mktemp`
grep nothing $n | sed -e 's,.*nothing provides perl(,,; s,).*,,' | sort | uniq -c | sort -n > $n2
for i in `sed -e 's,^perl-,,; s,-,::,g' $s` ; do grep " $i\$" $n2 ; done | sort -nr | head 

