---
abstract: 'Generate a spec file for a CPAN module'
author:
  - 'openSUSE perl maintainers'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: cpanspec
requires:
  Archive::Tar: 0
  Archive::Zip: 0
  Carp: 0
  Cwd: 0
  File::Basename: 0
  File::Path: 0
  File::Temp: 0
  FileHandle: 0
  Getopt::Long: 0
  LWP::UserAgent: 0
  Module::CoreList: 0
  POSIX: 0
  PPI::Document: 0
  Parse::CPAN::Packages: 0
  Pod::POM: 0
  Pod::POM::View::Text: 0
  Pod::Simple::TextContent: 0
  Pod::Usage: 0
  Text::Autoformat: 0
  YAML: 0
  locale: 0

recommends:
  IO::Uncompress::Bunzip2: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.79.01
